---
framework: jasmine
tier: small

postMerge:
  pattern: 
    -  "./test/weex/**/*[sS]pec.js"
preMerge:
  pattern:
    -  "./test/weex/**/*[sS]pec.js"
preRun:
     command:
        - npm i
        - npm run build:weex
postRun:
     command:
        - node --version
version: 1.0
parallelism : 4
configFile : "./test/weex/jasmine.js"
